include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    flutter_style_todos: false
    cascade_invocations: false
    sort_pub_dependencies: false
    deprecated_member_use_from_same_package: false