name: flutter_map_plugins
packages:
  - flutter_map_*
  - vector_map_tiles_*
  - example

scripts:
  test:
    description: Run tests of all packages
    run: melos exec --dir-exists="test"--fail-fast flutter test --no-pub
  pub_get:
    description: Run `pub get` for all packages
    run: melos exec --file-exists="pubspec.yaml" --concurrency 1 --fail-fast flutter pub get
  pub_upgrade:
    description: Run `pub upgrade` for all packages
    run: melos exec --file-exists="pubspec.yaml" --concurrency 1 --fail-fast flutter pub upgrade
  pub_outdated:
    description: Run `pub outdated` for all packages
    run: melos exec --file-exists="pubspec.yaml" --concurrency 1 --fail-fast flutter pub outdated
  package_score:
    description: Run pana for all packages
    run: melos exec --fail-fast --concurrency 1 --no-private pana --exit-code-threshold 0 --no-dartdoc .
  test_with_coverage:
    description: Run tests of all packages with coverage and merge its results
    run: |
      melos exec rm -rf coverage 
      melos exec --dir-exists="test" --fail-fast flutter pub get
      melos exec --dir-exists="test" --fail-fast flutter test --no-pub -r expanded --coverage
      melos exec -c 1 --file-exists=coverage/lcov.info coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/filtered.lcov.info --filters \.g\.dart
      coverde value -i coverage/filtered.lcov.info > MELOS_ROOT_PATH/coverage/result.txt