name: flutter_map_plugins
packages:
  - flutter_map_*
  - vector_map_tiles_*

scripts:
  analyze:
    description: Run `dart analyze` in all packages
    run: melos exec dart analyze .
  test:
    description: Run tests of all packages
    run: melos exec --dir-exists="test" --fail-fast flutter test --no-pub
  test_with_coverage:
    description: Run tests of all packages with coverage and merge its results
    run: |
      melos exec rm -rf coverage 
      melos exec --dir-exists="test" --fail-fast flutter test --no-pub -r expanded --coverage
      melos exec -c 1 --file-exists=coverage/lcov.info coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/filtered.lcov.info --filters \.g\.dart
      coverde value -i coverage/filtered.lcov.info > MELOS_ROOT_PATH/coverage/result.txt