name: flutter_map_mbtiles
description: Raster and Vector MBTiles TileProvider for flutter_map
version: 0.1.0
repository: https://github.com/josxha/flutter_map_mbtiles
issue_tracker: https://github.com/josxha/flutter_map_mbtiles/issues
topics: [ flutter-map, mbtiles, map ]

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0
  mbtiles: ^0.1.0
  sqlite3_flutter_libs: ^0.5.18

dev_dependencies:
  total_lints: ^3.2.0

dependency_overrides:
  vector_map_tiles:
    git:
      url: https://github.com/aovooyov/flutter-vector-map-tiles.git
      ref: main