name: Bug Report
description: Report a bug
title: "[BUG] <title>"
labels: [ "bug" ]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: For what is your bug report?
      options:
        - "other"
        - "flutter_map_cache"
        - "flutter_map_compass"
        - "flutter_map_maplibre"
        - "flutter_map_mbtiles"
        - "flutter_map_pmtiles"
        - "vector_map_tiles_mbtiles"
        - "vector_map_tiles_pmtiles"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Bug Description
      description: Please give a quick description about the bug you found.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please list the steps required to reproduce the problem one by one.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Results
      description: Please describe what is expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Results
      description: Please describe what is actually happening.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Code Sample
      description: |
        Please paste the code of how you use the package below between the lines with the backticks.
        
        Note: Please do not upload screenshots of text. Instead, use code blocks
        or the above mentioned ways to upload your code sample.
      value: |
        ```dart
        // Paste your code here
        ```
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platforms
      description: On what platforms does the bug happen?
      options: [ "all", "android", "iOS", "web", "windows", "macOS", "linux" ]
    validations:
      required: true