blank_issues_enabled: true
contact_links:
  - name: "Ask a Question"
    url: https://github.com/josxha/flutter-maplibre/discussions/new?category=q-a
    about: "If you have a question about using a Package"
  - name: "Start a Discussion"
    url: https://github.com/josxha/flutter-maplibre/discussions/new?category=general
    about: "Start a discussion on some topic"
  - name: "Share some Idea"
    url: https://github.com/josxha/flutter-maplibre/discussions/new?category=ideas
    about: "Share an idea, that isn't quite ready for a feature request"
  - name: Discord Server
    url: https://discord.gg/BwpEsjqMAH
    about: You can find me on the flutter_map Discord server as @josxha.
