// Mocks generated by Mockito 5.4.4 from annotations
// in vector_map_tiles_mbtiles/test/utils/common.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:typed_data' as _i4;

import 'package:mbtiles/src/mbtiles.dart' as _i3;
import 'package:mbtiles/src/model/mbtiles_metadata.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMbTilesMetadata_0 extends _i1.SmartFake
    implements _i2.MbTilesMetadata {
  _FakeMbTilesMetadata_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MbTiles].
///
/// See the documentation for Mockito's code generation for more information.
class MockMbTiles extends _i1.Mock implements _i3.MbTiles {
  @override
  bool get editable => (super.noSuchMethod(
        Invocation.getter(#editable),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.MbTilesMetadata getMetadata({bool? allowCache = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMetadata,
          [],
          {#allowCache: allowCache},
        ),
        returnValue: _FakeMbTilesMetadata_0(
          this,
          Invocation.method(
            #getMetadata,
            [],
            {#allowCache: allowCache},
          ),
        ),
        returnValueForMissingStub: _FakeMbTilesMetadata_0(
          this,
          Invocation.method(
            #getMetadata,
            [],
            {#allowCache: allowCache},
          ),
        ),
      ) as _i2.MbTilesMetadata);

  @override
  _i4.Uint8List? getTile({
    required int? z,
    required int? x,
    required int? y,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTile,
          [],
          {
            #z: z,
            #x: x,
            #y: y,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i4.Uint8List?);

  @override
  void createTables() => super.noSuchMethod(
        Invocation.method(
          #createTables,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void putTile({
    required int? z,
    required int? x,
    required int? y,
    required _i4.Uint8List? bytes,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #putTile,
          [],
          {
            #z: z,
            #x: x,
            #y: y,
            #bytes: bytes,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMetadata(_i2.MbTilesMetadata? metadata) => super.noSuchMethod(
        Invocation.method(
          #setMetadata,
          [metadata],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
