name: Build Android
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    name: Build Android
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Build APK
        working-directory: example
        run: flutter build apk
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: example/build/app/outputs/flutter-apk/app-release.apk
